name: Spring Boot CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package

      - name: Run Tests
        run: mvn test

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push Docker Image
        env:
          AWS_REGION: us-east-1
          ECR_REPOSITORY: springboot-shotnews
        run: |
          IMAGE_TAG=$(date +%s)
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG <AWS_ACCOUNT_ID>.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
          docker push <AWS_ACCOUNT_ID>.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to AWS EKS
        run: |
          kubectl apply -f kubernetes.yaml
          kubectl rollout restart deployment springboot-shotnews
